// Generated by scripts/gen_arrow_abi.py. Do not edit.

#ifndef IRX_ARROW_ABI_GENERATED_H_INCLUDED
#define IRX_ARROW_ABI_GENERATED_H_INCLUDED

#include <stddef.h>
#include <stdint.h>

#include "irx_arrow_c_abi.h"
#include "irx_buffer_runtime.h"

#if defined(_WIN32) && !defined(IRX_ARROW_STATIC)
#if defined(IRX_ARROW_BUILDING_RUNTIME)
#define IRX_ARROW_EXPORT __declspec(dllexport)
#else
#define IRX_ARROW_EXPORT __declspec(dllimport)
#endif
#define IRX_ARROW_CALL __cdecl
#elif defined(__GNUC__) || defined(__clang__)
#define IRX_ARROW_EXPORT __attribute__((visibility("default")))
#define IRX_ARROW_CALL
#else
#define IRX_ARROW_EXPORT
#define IRX_ARROW_CALL
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define IRX_ARROW_ABI_VERSION_MAJOR UINT32_C(1)
#define IRX_ARROW_ABI_VERSION_MINOR UINT32_C(5)
#define IRX_ARROW_ABI_VERSION_PATCH UINT32_C(0)
#define IRX_ARROW_ABI_VERSION \
  ((IRX_ARROW_ABI_VERSION_MAJOR << 16) | \
   (IRX_ARROW_ABI_VERSION_MINOR << 8) | \
   IRX_ARROW_ABI_VERSION_PATCH)
#define IRX_ARROW_ABI_VERSION_MAJOR_OF(version) \
  ((uint32_t)(version) >> 16)
#define IRX_ARROW_ABI_VERSION_MINOR_OF(version) \
  (((uint32_t)(version) >> 8) & UINT32_C(0xff))
#define IRX_ARROW_ABI_VERSION_IS_COMPATIBLE(runtime, required) \
  (IRX_ARROW_ABI_VERSION_MAJOR_OF(runtime) == \
       IRX_ARROW_ABI_VERSION_MAJOR_OF(required) && \
   IRX_ARROW_ABI_VERSION_MINOR_OF(runtime) >= \
       IRX_ARROW_ABI_VERSION_MINOR_OF(required))

typedef int32_t irx_arrow_status;

enum irx_arrow_status_code {
  IRX_ARROW_STATUS_OK = 0,
  IRX_ARROW_STATUS_END_OF_STREAM = 1,
  IRX_ARROW_STATUS_INVALID_ARGUMENT = 100,
  IRX_ARROW_STATUS_NULL_POINTER = 101,
  IRX_ARROW_STATUS_INVALID_STATE = 102,
  IRX_ARROW_STATUS_TYPE_MISMATCH = 103,
  IRX_ARROW_STATUS_SCHEMA_MISMATCH = 104,
  IRX_ARROW_STATUS_INDEX_OUT_OF_BOUNDS = 105,
  IRX_ARROW_STATUS_OVERFLOW = 106,
  IRX_ARROW_STATUS_NOT_SUPPORTED = 107,
  IRX_ARROW_STATUS_ABI_MISMATCH = 108,
  IRX_ARROW_STATUS_OUT_OF_MEMORY = 200,
  IRX_ARROW_STATUS_RESOURCE_EXHAUSTED = 201,
  IRX_ARROW_STATUS_IO_ERROR = 300,
  IRX_ARROW_STATUS_CANCELLED = 301,
  IRX_ARROW_STATUS_ARROW_ERROR = 400,
  IRX_ARROW_STATUS_INTERNAL = 401,
};

typedef int32_t irx_arrow_status_category;

enum irx_arrow_status_category_code {
  IRX_ARROW_STATUS_CATEGORY_SUCCESS = 0,
  IRX_ARROW_STATUS_CATEGORY_CONTROL = 1,
  IRX_ARROW_STATUS_CATEGORY_INVALID = 2,
  IRX_ARROW_STATUS_CATEGORY_RESOURCE = 3,
  IRX_ARROW_STATUS_CATEGORY_IO = 4,
  IRX_ARROW_STATUS_CATEGORY_INTERNAL = 5,
  IRX_ARROW_STATUS_CATEGORY_UNKNOWN = 6,
};

typedef int32_t irx_arrow_runtime_feature_id;

enum irx_arrow_runtime_feature_id_code {
  IRX_ARROW_RUNTIME_FEATURE_UNKNOWN = 0,
  IRX_ARROW_RUNTIME_FEATURE_CORE = 1,
  IRX_ARROW_RUNTIME_FEATURE_ARRAY = 2,
  IRX_ARROW_RUNTIME_FEATURE_TENSOR = 3,
  IRX_ARROW_RUNTIME_FEATURE_DATAFRAME = 4,
  IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH = 5,
};

#define IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION_MAJOR UINT32_C(1)
#define IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION_MINOR UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION_PATCH UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION \
  ((IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION_MAJOR << 16) | \
   (IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION_MINOR << 8) | \
   IRX_ARROW_RUNTIME_FEATURE_CORE_CONTRACT_VERSION_PATCH)

#define IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION_MAJOR UINT32_C(1)
#define IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION_MINOR UINT32_C(5)
#define IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION_PATCH UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION \
  ((IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION_MAJOR << 16) | \
   (IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION_MINOR << 8) | \
   IRX_ARROW_RUNTIME_FEATURE_ARRAY_CONTRACT_VERSION_PATCH)

#define IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION_MAJOR UINT32_C(1)
#define IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION_MINOR UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION_PATCH UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION \
  ((IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION_MAJOR << 16) | \
   (IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION_MINOR << 8) | \
   IRX_ARROW_RUNTIME_FEATURE_TENSOR_CONTRACT_VERSION_PATCH)

#define IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION_MAJOR UINT32_C(1)
#define IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION_MINOR UINT32_C(2)
#define IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION_PATCH UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION \
  ((IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION_MAJOR << 16) | \
   (IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION_MINOR << 8) | \
   IRX_ARROW_RUNTIME_FEATURE_DATAFRAME_CONTRACT_VERSION_PATCH)

#define IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION_MAJOR UINT32_C(1)
#define IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION_MINOR UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION_PATCH UINT32_C(0)
#define IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION \
  ((IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION_MAJOR << 16) | \
   (IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION_MINOR << 8) | \
   IRX_ARROW_RUNTIME_FEATURE_RECORD_BATCH_CONTRACT_VERSION_PATCH)

typedef struct irx_arrow_error_handle irx_arrow_error_handle;
typedef struct irx_arrow_type_handle irx_arrow_type_handle;
typedef struct irx_arrow_schema_handle irx_arrow_schema_handle;
typedef struct irx_arrow_scalar_handle irx_arrow_scalar_handle;
typedef struct irx_arrow_array_builder_handle irx_arrow_array_builder_handle;
typedef struct irx_arrow_array_handle irx_arrow_array_handle;
typedef struct irx_arrow_chunked_array_handle irx_arrow_chunked_array_handle;
typedef struct irx_arrow_record_batch_handle irx_arrow_record_batch_handle;
typedef struct irx_arrow_table_handle irx_arrow_table_handle;
typedef struct irx_arrow_tensor_builder_handle irx_arrow_tensor_builder_handle;
typedef struct irx_arrow_tensor_handle irx_arrow_tensor_handle;
typedef struct irx_arrow_stream_handle irx_arrow_stream_handle;
typedef struct irx_arrow_dataset_handle irx_arrow_dataset_handle;
typedef struct irx_arrow_execution_plan_handle irx_arrow_execution_plan_handle;
typedef struct irx_arrow_field_handle irx_arrow_field_handle;

typedef int32_t irx_arrow_handle_kind;

enum irx_arrow_handle_kind_code {
  IRX_ARROW_HANDLE_KIND_UNKNOWN = 0,
  IRX_ARROW_HANDLE_KIND_ERROR = 1,
  IRX_ARROW_HANDLE_KIND_TYPE = 2,
  IRX_ARROW_HANDLE_KIND_SCHEMA = 3,
  IRX_ARROW_HANDLE_KIND_SCALAR = 4,
  IRX_ARROW_HANDLE_KIND_ARRAY_BUILDER = 5,
  IRX_ARROW_HANDLE_KIND_ARRAY = 6,
  IRX_ARROW_HANDLE_KIND_CHUNKED_ARRAY = 7,
  IRX_ARROW_HANDLE_KIND_RECORD_BATCH = 8,
  IRX_ARROW_HANDLE_KIND_TABLE = 9,
  IRX_ARROW_HANDLE_KIND_TENSOR_BUILDER = 10,
  IRX_ARROW_HANDLE_KIND_TENSOR = 11,
  IRX_ARROW_HANDLE_KIND_STREAM = 12,
  IRX_ARROW_HANDLE_KIND_DATASET = 13,
  IRX_ARROW_HANDLE_KIND_EXECUTION_PLAN = 14,
  IRX_ARROW_HANDLE_KIND_FIELD = 15,
};

typedef int32_t irx_arrow_handle_ownership;

enum irx_arrow_handle_ownership_code {
  IRX_ARROW_HANDLE_OWNERSHIP_UNKNOWN = 0,
  IRX_ARROW_HANDLE_OWNERSHIP_SHARED = 1,
  IRX_ARROW_HANDLE_OWNERSHIP_UNIQUE = 2,
};

enum irx_arrow_type_id {
  IRX_ARROW_TYPE_UNKNOWN = 0,
  IRX_ARROW_TYPE_INT32 = 1,
  IRX_ARROW_TYPE_INT8 = 2,
  IRX_ARROW_TYPE_INT16 = 3,
  IRX_ARROW_TYPE_INT64 = 4,
  IRX_ARROW_TYPE_UINT8 = 5,
  IRX_ARROW_TYPE_UINT16 = 6,
  IRX_ARROW_TYPE_UINT32 = 7,
  IRX_ARROW_TYPE_UINT64 = 8,
  IRX_ARROW_TYPE_FLOAT32 = 9,
  IRX_ARROW_TYPE_FLOAT64 = 10,
  IRX_ARROW_TYPE_BOOL = 11,
  IRX_ARROW_TYPE_FLOAT16 = 12,
};

IRX_ARROW_EXPORT uint32_t IRX_ARROW_CALL irx_arrow_abi_version(void);

/*
 * Query one runtime feature contract.
 * A zero required version discovers any implemented
 * contract. Unknown IDs return OK with unavailable and
 * version zero. Known incompatible IDs report their
 * supported version.
 */
IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_runtime_has_feature(
    irx_arrow_runtime_feature_id feature_id,
    uint32_t required_contract_version,
    int32_t* out_available,
    uint32_t* out_supported_contract_version,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status_category IRX_ARROW_CALL irx_arrow_status_get_category(
    irx_arrow_status status);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_handle_kind_of(
    const void* handle,
    irx_arrow_handle_kind* out_kind,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_handle_ownership_of(
    const void* handle,
    irx_arrow_handle_ownership* out_ownership,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_snapshot(
    irx_arrow_error_handle** out_error,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_code(
    const irx_arrow_error_handle* error,
    irx_arrow_status* out_code,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_operation(
    const irx_arrow_error_handle* error,
    const char** out_operation,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_message(
    const irx_arrow_error_handle* error,
    const char** out_message,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_upstream_detail(
    const irx_arrow_error_handle* error,
    const char** out_upstream_detail,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_retain(
    const irx_arrow_error_handle* error,
    irx_arrow_error_handle** out_error,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_error_release(
    irx_arrow_error_handle** error,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_import_copy(
    const struct ArrowSchema* schema,
    irx_arrow_schema_handle** out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_export(
    const irx_arrow_schema_handle* schema,
    struct ArrowSchema* out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_type_id(
    const irx_arrow_schema_handle* schema,
    int32_t* out_type_id,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_is_nullable(
    const irx_arrow_schema_handle* schema,
    int32_t* out_is_nullable,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_retain(
    const irx_arrow_schema_handle* schema,
    irx_arrow_schema_handle** out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_release(
    irx_arrow_schema_handle** schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_new(
    int32_t type_id,
    irx_arrow_array_builder_handle** out_builder,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_append_null(
    irx_arrow_array_builder_handle* builder,
    int64_t count,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_append_int(
    irx_arrow_array_builder_handle* builder,
    int64_t value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_append_uint(
    irx_arrow_array_builder_handle* builder,
    uint64_t value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_append_double(
    irx_arrow_array_builder_handle* builder,
    double value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_int32_new(
    irx_arrow_array_builder_handle** out_builder,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_append_int32(
    irx_arrow_array_builder_handle* builder,
    int32_t value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_finish(
    irx_arrow_array_builder_handle** builder,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_release(
    irx_arrow_array_builder_handle** builder,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_length(
    const irx_arrow_array_handle* array,
    int64_t* out_length,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_offset(
    const irx_arrow_array_handle* array,
    int64_t* out_offset,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_null_count(
    const irx_arrow_array_handle* array,
    int64_t* out_null_count,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_type_id(
    const irx_arrow_array_handle* array,
    int32_t* out_type_id,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_is_nullable(
    const irx_arrow_array_handle* array,
    int32_t* out_is_nullable,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_has_validity_bitmap(
    const irx_arrow_array_handle* array,
    int32_t* out_has_validity_bitmap,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_can_borrow_buffer_view(
    const irx_arrow_array_handle* array,
    int32_t* out_can_borrow,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_schema_copy(
    const irx_arrow_array_handle* array,
    irx_arrow_schema_handle** out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_export(
    const irx_arrow_array_handle* array,
    struct ArrowArray* out_array,
    struct ArrowSchema* out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_import(
    const struct ArrowArray* array,
    const struct ArrowSchema* schema,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_import_copy(
    const struct ArrowArray* array,
    const struct ArrowSchema* schema,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_import_move(
    struct ArrowArray* array,
    struct ArrowSchema* schema,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_validity_bitmap(
    const irx_arrow_array_handle* array,
    const void** out_data,
    int64_t* out_offset_bits,
    int64_t* out_length_bits,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_borrow_buffer_view(
    const irx_arrow_array_handle* array,
    irx_buffer_view* out_view,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_retain(
    const irx_arrow_array_handle* array,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_release(
    irx_arrow_array_handle** array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_record_batch_import_move(
    struct ArrowArray* array,
    struct ArrowSchema* schema,
    irx_arrow_record_batch_handle** out_batch,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_record_batch_export(
    const irx_arrow_record_batch_handle* batch,
    struct ArrowArray* out_array,
    struct ArrowSchema* out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_record_batch_num_rows(
    const irx_arrow_record_batch_handle* batch,
    int64_t* out_num_rows,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_record_batch_num_columns(
    const irx_arrow_record_batch_handle* batch,
    int64_t* out_num_columns,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_record_batch_retain(
    const irx_arrow_record_batch_handle* batch,
    irx_arrow_record_batch_handle** out_batch,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_record_batch_release(
    irx_arrow_record_batch_handle** batch,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_builder_new(
    int32_t type_id,
    int32_t ndim,
    const int64_t* shape,
    const int64_t* strides,
    irx_arrow_tensor_builder_handle** out_builder,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_builder_append_int(
    irx_arrow_tensor_builder_handle* builder,
    int64_t value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_builder_append_uint(
    irx_arrow_tensor_builder_handle* builder,
    uint64_t value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_builder_append_double(
    irx_arrow_tensor_builder_handle* builder,
    double value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_builder_finish(
    irx_arrow_tensor_builder_handle** builder,
    irx_arrow_tensor_handle** out_tensor,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_builder_release(
    irx_arrow_tensor_builder_handle** builder,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_type_id(
    const irx_arrow_tensor_handle* tensor,
    int32_t* out_type_id,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_ndim(
    const irx_arrow_tensor_handle* tensor,
    int32_t* out_ndim,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_size(
    const irx_arrow_tensor_handle* tensor,
    int64_t* out_size,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_shape(
    const irx_arrow_tensor_handle* tensor,
    const int64_t** out_shape,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_strides(
    const irx_arrow_tensor_handle* tensor,
    const int64_t** out_strides,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_borrow_buffer_view(
    const irx_arrow_tensor_handle* tensor,
    irx_buffer_view* out_view,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_retain(
    const irx_arrow_tensor_handle* tensor,
    irx_arrow_tensor_handle** out_tensor,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_tensor_release(
    irx_arrow_tensor_handle** tensor,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_new_from_arrays(
    int64_t column_count,
    const char** names,
    irx_arrow_array_handle** arrays,
    irx_arrow_table_handle** out_table,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_num_rows(
    const irx_arrow_table_handle* table,
    int64_t* out_num_rows,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_num_columns(
    const irx_arrow_table_handle* table,
    int64_t* out_num_columns,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_column_by_name(
    const irx_arrow_table_handle* table,
    const char* name,
    irx_arrow_chunked_array_handle** out_column,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_column_by_index(
    const irx_arrow_table_handle* table,
    int32_t index,
    irx_arrow_chunked_array_handle** out_column,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_retain(
    const irx_arrow_table_handle* table,
    irx_arrow_table_handle** out_table,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_release(
    irx_arrow_table_handle** table,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_array_retain(
    const irx_arrow_chunked_array_handle* column,
    irx_arrow_chunked_array_handle** out_column,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_array_release(
    irx_arrow_chunked_array_handle** column,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT void IRX_ARROW_CALL irx_arrow_tensor_release_callback(
    void* tensor);

IRX_ARROW_EXPORT const char* IRX_ARROW_CALL irx_arrow_last_error(void);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_import_copy(
    const struct ArrowSchema* schema,
    irx_arrow_type_handle** out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_export(
    const irx_arrow_type_handle* value,
    struct ArrowSchema* out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_retain(
    const irx_arrow_type_handle* value,
    irx_arrow_type_handle** out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_release(
    irx_arrow_type_handle** value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_import_copy(
    const struct ArrowSchema* schema,
    irx_arrow_field_handle** out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_export(
    const irx_arrow_field_handle* value,
    struct ArrowSchema* out_schema,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_retain(
    const irx_arrow_field_handle* value,
    irx_arrow_field_handle** out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_release(
    irx_arrow_field_handle** value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_equals(
    const irx_arrow_type_handle* left,
    const irx_arrow_type_handle* right,
    int32_t* out_equal,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_equals(
    const irx_arrow_field_handle* left,
    const irx_arrow_field_handle* right,
    int32_t* out_equal,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_equals(
    const irx_arrow_schema_handle* left,
    const irx_arrow_schema_handle* right,
    int32_t* out_equal,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_num_fields(
    const irx_arrow_type_handle* value,
    int64_t* out_count,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_field(
    const irx_arrow_type_handle* value,
    int64_t index,
    irx_arrow_field_handle** out_field,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_num_fields(
    const irx_arrow_schema_handle* value,
    int64_t* out_count,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_schema_field(
    const irx_arrow_schema_handle* value,
    int64_t index,
    irx_arrow_field_handle** out_field,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_type(
    const irx_arrow_field_handle* value,
    irx_arrow_type_handle** out_type,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_nullable(
    const irx_arrow_field_handle* value,
    int32_t* out_nullable,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_type_bit_width(
    const irx_arrow_type_handle* value,
    int64_t* out_width,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_field_name_copy(
    const irx_arrow_field_handle* value,
    const char** out_name,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_get_int(
    const irx_arrow_array_handle* array,
    int64_t index,
    int32_t* out_valid,
    int64_t* out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_get_uint(
    const irx_arrow_array_handle* array,
    int64_t index,
    int32_t* out_valid,
    uint64_t* out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_get_double(
    const irx_arrow_array_handle* array,
    int64_t index,
    int32_t* out_valid,
    double* out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_slice(
    const irx_arrow_array_handle* array,
    int64_t offset,
    int64_t length,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_concat(
    const irx_arrow_array_handle* lhs,
    const irx_arrow_array_handle* rhs,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_copy(
    const irx_arrow_array_handle* array,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_equal(
    const irx_arrow_array_handle* lhs,
    const irx_arrow_array_handle* rhs,
    int32_t* out_equal,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_finish_typed(
    irx_arrow_array_builder_handle** builder,
    int32_t nullable,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_reserve(
    irx_arrow_array_builder_handle* builder,
    int64_t additional,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_length(
    const irx_arrow_array_builder_handle* builder,
    int64_t* out_length,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_build(
    irx_arrow_array_builder_handle* builder,
    int32_t nullable,
    irx_arrow_array_handle** out_array,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_new(
    int32_t type_id,
    int32_t nullable,
    const void** chunks,
    int64_t count,
    irx_arrow_chunked_array_handle** out_value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_length(
    const irx_arrow_chunked_array_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_null_count(
    const irx_arrow_chunked_array_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_num_chunks(
    const irx_arrow_chunked_array_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_get_int(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    int32_t* valid,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_get_uint(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    int32_t* valid,
    uint64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_get_double(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    int32_t* valid,
    double* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_chunk(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    irx_arrow_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_combine(
    const irx_arrow_chunked_array_handle* value,
    irx_arrow_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_slice(
    const irx_arrow_chunked_array_handle* value,
    int64_t offset,
    int64_t length,
    irx_arrow_chunked_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_copy(
    const irx_arrow_chunked_array_handle* value,
    irx_arrow_chunked_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_concat(
    const irx_arrow_chunked_array_handle* lhs,
    const irx_arrow_chunked_array_handle* rhs,
    irx_arrow_chunked_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_equal(
    const irx_arrow_chunked_array_handle* lhs,
    const irx_arrow_chunked_array_handle* rhs,
    int32_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_new_typed(
    const irx_arrow_schema_handle* schema,
    const void** columns,
    int64_t count,
    int64_t rows,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_rows(
    const irx_arrow_record_batch_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_columns(
    const irx_arrow_record_batch_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_schema(
    const irx_arrow_record_batch_handle* value,
    irx_arrow_schema_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_column_checked(
    const irx_arrow_record_batch_handle* value,
    int64_t index,
    const irx_arrow_field_handle* expected,
    irx_arrow_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_slice(
    const irx_arrow_record_batch_handle* value,
    int64_t offset,
    int64_t length,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_select(
    const irx_arrow_record_batch_handle* value,
    const int64_t* indices,
    int64_t count,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_with_schema(
    const irx_arrow_record_batch_handle* value,
    const irx_arrow_schema_handle* schema,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_set_column(
    const irx_arrow_record_batch_handle* value,
    int64_t index,
    const irx_arrow_field_handle* field,
    const irx_arrow_array_handle* column,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_remove(
    const irx_arrow_record_batch_handle* value,
    int64_t index,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_new_typed(
    const irx_arrow_schema_handle* schema,
    const void** columns,
    int64_t count,
    int64_t rows,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_rows(
    const irx_arrow_table_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_columns(
    const irx_arrow_table_handle* value,
    int64_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_schema(
    const irx_arrow_table_handle* value,
    irx_arrow_schema_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_column_checked(
    const irx_arrow_table_handle* value,
    int64_t index,
    const irx_arrow_field_handle* expected,
    irx_arrow_chunked_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_slice(
    const irx_arrow_table_handle* value,
    int64_t offset,
    int64_t length,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_select(
    const irx_arrow_table_handle* value,
    const int64_t* indices,
    int64_t count,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_with_schema(
    const irx_arrow_table_handle* value,
    const irx_arrow_schema_handle* schema,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_set_column(
    const irx_arrow_table_handle* value,
    int64_t index,
    const irx_arrow_field_handle* field,
    const irx_arrow_chunked_array_handle* column,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_remove(
    const irx_arrow_table_handle* value,
    int64_t index,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_to_table(
    const irx_arrow_record_batch_handle* value,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_to_batch(
    const irx_arrow_table_handle* value,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_combine(
    const irx_arrow_table_handle* value,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_retain(
    const irx_arrow_scalar_handle* value,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_release(
    irx_arrow_scalar_handle** value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_parse(
    const irx_arrow_type_handle* type,
    const char* text,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_from_array(
    const irx_arrow_type_handle* type,
    const irx_arrow_array_handle* value,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_from_fields(
    const irx_arrow_type_handle* type,
    const void** values,
    int64_t count,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_dictionary(
    const irx_arrow_type_handle* type,
    const irx_arrow_scalar_handle* index,
    const irx_arrow_array_handle* values,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_wrap(
    const irx_arrow_type_handle* type,
    const irx_arrow_scalar_handle* value,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_union(
    const irx_arrow_type_handle* type,
    const char* name,
    const irx_arrow_scalar_handle* value,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_interval(
    const irx_arrow_type_handle* type,
    const int64_t* values,
    int64_t count,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_equal(
    const irx_arrow_scalar_handle* left,
    const irx_arrow_scalar_handle* right,
    int32_t* output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_text(
    const irx_arrow_scalar_handle* value,
    const char** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_values(
    const irx_arrow_scalar_handle* value,
    irx_arrow_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_field(
    const irx_arrow_scalar_handle* value,
    const char* name,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_get_scalar(
    const irx_arrow_array_handle* value,
    int64_t index,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_get_scalar(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_new_logical(
    const irx_arrow_type_handle* type,
    irx_arrow_array_builder_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_builder_append_scalar(
    irx_arrow_array_builder_handle* builder,
    const irx_arrow_scalar_handle* value,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_chunked_new_logical(
    const irx_arrow_type_handle* type,
    int32_t nullable,
    const void** chunks,
    int64_t count,
    irx_arrow_chunked_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_from_bytes(
    const irx_arrow_type_handle* type,
    const irx_arrow_array_handle* value,
    irx_arrow_scalar_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_scalar_bytes(
    const irx_arrow_scalar_handle* value,
    irx_arrow_array_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_batch_take(
    const irx_arrow_record_batch_handle* value,
    const irx_arrow_array_handle* indices,
    irx_arrow_record_batch_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_table_take(
    const irx_arrow_table_handle* value,
    const irx_arrow_array_handle* indices,
    irx_arrow_table_handle** output,
    irx_arrow_error_handle** out_failure);

IRX_ARROW_EXPORT irx_arrow_status IRX_ARROW_CALL irx_arrow_array_from_buffer(
    int32_t type_id,
    irx_buffer_view* view,
    irx_arrow_array_handle** output,
    irx_arrow_error_handle** out_failure);

#ifdef __cplusplus
}
#endif

#if defined(__cplusplus)
#define IRX_ARROW_ABI_STATIC_ASSERT static_assert
#define IRX_ARROW_ABI_ALIGNOF alignof
#else
#define IRX_ARROW_ABI_STATIC_ASSERT _Static_assert
#define IRX_ARROW_ABI_ALIGNOF _Alignof
#endif
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(irx_arrow_status) == 4,
    "irx_arrow_status must be 32-bit");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(irx_arrow_status_category) == 4,
    "status category must be 32-bit");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(irx_arrow_runtime_feature_id) == 4,
    "runtime feature ID must be 32-bit");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(irx_arrow_handle_kind) == 4,
    "handle kind must be 32-bit");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(irx_arrow_handle_ownership) == 4,
    "handle ownership must be 32-bit");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(enum irx_arrow_type_id) == 4,
    "type ID constants must be 32-bit");

#if UINTPTR_MAX == UINT64_MAX
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(irx_buffer_view) == 64,
    "unexpected 64-bit buffer-view size");
IRX_ARROW_ABI_STATIC_ASSERT(
    IRX_ARROW_ABI_ALIGNOF(irx_buffer_view) == 8,
    "unexpected 64-bit buffer-view alignment");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, data) == 0,
    "unexpected data offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, owner) == 8,
    "unexpected owner offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, dtype) == 16,
    "unexpected dtype offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, ndim) == 24,
    "unexpected ndim offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, shape) == 32,
    "unexpected shape offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, strides) == 40,
    "unexpected strides offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, offset_bytes) == 48,
    "unexpected byte offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(irx_buffer_view, flags) == 56,
    "unexpected flags offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(struct ArrowSchema) == 72,
    "unexpected ArrowSchema size");
IRX_ARROW_ABI_STATIC_ASSERT(
    IRX_ARROW_ABI_ALIGNOF(struct ArrowSchema) == 8,
    "unexpected ArrowSchema alignment");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(struct ArrowSchema, flags) == 24,
    "unexpected ArrowSchema flags offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(struct ArrowSchema, release) == 56,
    "unexpected ArrowSchema release offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(struct ArrowArray) == 80,
    "unexpected ArrowArray size");
IRX_ARROW_ABI_STATIC_ASSERT(
    IRX_ARROW_ABI_ALIGNOF(struct ArrowArray) == 8,
    "unexpected ArrowArray alignment");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(struct ArrowArray, buffers) == 40,
    "unexpected ArrowArray buffers offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(struct ArrowArray, release) == 64,
    "unexpected ArrowArray release offset");
IRX_ARROW_ABI_STATIC_ASSERT(
    sizeof(struct ArrowArrayStream) == 40,
    "unexpected ArrowArrayStream size");
IRX_ARROW_ABI_STATIC_ASSERT(
    IRX_ARROW_ABI_ALIGNOF(struct ArrowArrayStream) == 8,
    "unexpected ArrowArrayStream alignment");
IRX_ARROW_ABI_STATIC_ASSERT(
    offsetof(struct ArrowArrayStream, private_data) == 32,
    "unexpected ArrowArrayStream private-data offset");
#endif

#undef IRX_ARROW_ABI_ALIGNOF
#undef IRX_ARROW_ABI_STATIC_ASSERT

#endif
