// Generated by scripts/gen_arrow_abi.py. Do not edit.

#ifndef IRX_ARROW_ABI_INTERNAL_NAMES_GENERATED_H_INCLUDED
#define IRX_ARROW_ABI_INTERNAL_NAMES_GENERATED_H_INCLUDED

#define irx_arrow_abi_version \
  irx_arrow_internal_abi_version
#define irx_arrow_runtime_has_feature \
  irx_arrow_internal_runtime_has_feature
#define irx_arrow_status_get_category \
  irx_arrow_internal_status_get_category
#define irx_arrow_handle_kind_of \
  irx_arrow_internal_handle_kind_of
#define irx_arrow_handle_ownership_of \
  irx_arrow_internal_handle_ownership_of
#define irx_arrow_error_snapshot \
  irx_arrow_internal_error_snapshot
#define irx_arrow_error_code \
  irx_arrow_internal_error_code
#define irx_arrow_error_operation \
  irx_arrow_internal_error_operation
#define irx_arrow_error_message \
  irx_arrow_internal_error_message
#define irx_arrow_error_upstream_detail \
  irx_arrow_internal_error_upstream_detail
#define irx_arrow_error_retain \
  irx_arrow_internal_error_retain
#define irx_arrow_error_release \
  irx_arrow_internal_error_release
#define irx_arrow_schema_import_copy \
  irx_arrow_internal_schema_import_copy
#define irx_arrow_schema_export \
  irx_arrow_internal_schema_export
#define irx_arrow_schema_type_id \
  irx_arrow_internal_schema_type_id
#define irx_arrow_schema_is_nullable \
  irx_arrow_internal_schema_is_nullable
#define irx_arrow_schema_retain \
  irx_arrow_internal_schema_retain
#define irx_arrow_schema_release \
  irx_arrow_internal_schema_release
#define irx_arrow_array_builder_new \
  irx_arrow_internal_array_builder_new
#define irx_arrow_array_builder_append_null \
  irx_arrow_internal_array_builder_append_null
#define irx_arrow_array_builder_append_int \
  irx_arrow_internal_array_builder_append_int
#define irx_arrow_array_builder_append_uint \
  irx_arrow_internal_array_builder_append_uint
#define irx_arrow_array_builder_append_double \
  irx_arrow_internal_array_builder_append_double
#define irx_arrow_array_builder_int32_new \
  irx_arrow_internal_array_builder_int32_new
#define irx_arrow_array_builder_append_int32 \
  irx_arrow_internal_array_builder_append_int32
#define irx_arrow_array_builder_finish \
  irx_arrow_internal_array_builder_finish
#define irx_arrow_array_builder_release \
  irx_arrow_internal_array_builder_release
#define irx_arrow_array_length \
  irx_arrow_internal_array_length
#define irx_arrow_array_offset \
  irx_arrow_internal_array_offset
#define irx_arrow_array_null_count \
  irx_arrow_internal_array_null_count
#define irx_arrow_array_type_id \
  irx_arrow_internal_array_type_id
#define irx_arrow_array_is_nullable \
  irx_arrow_internal_array_is_nullable
#define irx_arrow_array_has_validity_bitmap \
  irx_arrow_internal_array_has_validity_bitmap
#define irx_arrow_array_can_borrow_buffer_view \
  irx_arrow_internal_array_can_borrow_buffer_view
#define irx_arrow_array_schema_copy \
  irx_arrow_internal_array_schema_copy
#define irx_arrow_array_export \
  irx_arrow_internal_array_export
#define irx_arrow_array_import \
  irx_arrow_internal_array_import
#define irx_arrow_array_import_copy \
  irx_arrow_internal_array_import_copy
#define irx_arrow_array_import_move \
  irx_arrow_internal_array_import_move
#define irx_arrow_array_validity_bitmap \
  irx_arrow_internal_array_validity_bitmap
#define irx_arrow_array_borrow_buffer_view \
  irx_arrow_internal_array_borrow_buffer_view
#define irx_arrow_array_retain \
  irx_arrow_internal_array_retain
#define irx_arrow_array_release \
  irx_arrow_internal_array_release
#define irx_arrow_record_batch_import_move \
  irx_arrow_internal_record_batch_import_move
#define irx_arrow_record_batch_export \
  irx_arrow_internal_record_batch_export
#define irx_arrow_record_batch_num_rows \
  irx_arrow_internal_record_batch_num_rows
#define irx_arrow_record_batch_num_columns \
  irx_arrow_internal_record_batch_num_columns
#define irx_arrow_record_batch_retain \
  irx_arrow_internal_record_batch_retain
#define irx_arrow_record_batch_release \
  irx_arrow_internal_record_batch_release
#define irx_arrow_tensor_builder_new \
  irx_arrow_internal_tensor_builder_new
#define irx_arrow_tensor_builder_append_int \
  irx_arrow_internal_tensor_builder_append_int
#define irx_arrow_tensor_builder_append_uint \
  irx_arrow_internal_tensor_builder_append_uint
#define irx_arrow_tensor_builder_append_double \
  irx_arrow_internal_tensor_builder_append_double
#define irx_arrow_tensor_builder_finish \
  irx_arrow_internal_tensor_builder_finish
#define irx_arrow_tensor_builder_release \
  irx_arrow_internal_tensor_builder_release
#define irx_arrow_tensor_type_id \
  irx_arrow_internal_tensor_type_id
#define irx_arrow_tensor_ndim \
  irx_arrow_internal_tensor_ndim
#define irx_arrow_tensor_size \
  irx_arrow_internal_tensor_size
#define irx_arrow_tensor_shape \
  irx_arrow_internal_tensor_shape
#define irx_arrow_tensor_strides \
  irx_arrow_internal_tensor_strides
#define irx_arrow_tensor_borrow_buffer_view \
  irx_arrow_internal_tensor_borrow_buffer_view
#define irx_arrow_tensor_retain \
  irx_arrow_internal_tensor_retain
#define irx_arrow_tensor_release \
  irx_arrow_internal_tensor_release
#define irx_arrow_table_new_from_arrays \
  irx_arrow_internal_table_new_from_arrays
#define irx_arrow_table_num_rows \
  irx_arrow_internal_table_num_rows
#define irx_arrow_table_num_columns \
  irx_arrow_internal_table_num_columns
#define irx_arrow_table_column_by_name \
  irx_arrow_internal_table_column_by_name
#define irx_arrow_table_column_by_index \
  irx_arrow_internal_table_column_by_index
#define irx_arrow_table_retain \
  irx_arrow_internal_table_retain
#define irx_arrow_table_release \
  irx_arrow_internal_table_release
#define irx_arrow_chunked_array_retain \
  irx_arrow_internal_chunked_array_retain
#define irx_arrow_chunked_array_release \
  irx_arrow_internal_chunked_array_release
#define irx_arrow_tensor_release_callback \
  irx_arrow_internal_tensor_release_callback
#define irx_arrow_last_error \
  irx_arrow_internal_last_error
#define irx_arrow_type_import_copy \
  irx_arrow_internal_type_import_copy
#define irx_arrow_type_export \
  irx_arrow_internal_type_export
#define irx_arrow_type_retain \
  irx_arrow_internal_type_retain
#define irx_arrow_type_release \
  irx_arrow_internal_type_release
#define irx_arrow_field_import_copy \
  irx_arrow_internal_field_import_copy
#define irx_arrow_field_export \
  irx_arrow_internal_field_export
#define irx_arrow_field_retain \
  irx_arrow_internal_field_retain
#define irx_arrow_field_release \
  irx_arrow_internal_field_release
#define irx_arrow_type_equals \
  irx_arrow_internal_type_equals
#define irx_arrow_field_equals \
  irx_arrow_internal_field_equals
#define irx_arrow_schema_equals \
  irx_arrow_internal_schema_equals
#define irx_arrow_type_num_fields \
  irx_arrow_internal_type_num_fields
#define irx_arrow_type_field \
  irx_arrow_internal_type_field
#define irx_arrow_schema_num_fields \
  irx_arrow_internal_schema_num_fields
#define irx_arrow_schema_field \
  irx_arrow_internal_schema_field
#define irx_arrow_field_type \
  irx_arrow_internal_field_type
#define irx_arrow_field_nullable \
  irx_arrow_internal_field_nullable
#define irx_arrow_type_bit_width \
  irx_arrow_internal_type_bit_width
#define irx_arrow_field_name_copy \
  irx_arrow_internal_field_name_copy
#define irx_arrow_array_get_int \
  irx_arrow_internal_array_get_int
#define irx_arrow_array_get_uint \
  irx_arrow_internal_array_get_uint
#define irx_arrow_array_get_double \
  irx_arrow_internal_array_get_double
#define irx_arrow_array_slice \
  irx_arrow_internal_array_slice
#define irx_arrow_array_concat \
  irx_arrow_internal_array_concat
#define irx_arrow_array_copy \
  irx_arrow_internal_array_copy
#define irx_arrow_array_equal \
  irx_arrow_internal_array_equal
#define irx_arrow_array_builder_finish_typed \
  irx_arrow_internal_array_builder_finish_typed
#define irx_arrow_array_builder_reserve \
  irx_arrow_internal_array_builder_reserve
#define irx_arrow_array_builder_length \
  irx_arrow_internal_array_builder_length
#define irx_arrow_array_builder_build \
  irx_arrow_internal_array_builder_build
#define irx_arrow_chunked_new \
  irx_arrow_internal_chunked_new
#define irx_arrow_chunked_length \
  irx_arrow_internal_chunked_length
#define irx_arrow_chunked_null_count \
  irx_arrow_internal_chunked_null_count
#define irx_arrow_chunked_num_chunks \
  irx_arrow_internal_chunked_num_chunks
#define irx_arrow_chunked_get_int \
  irx_arrow_internal_chunked_get_int
#define irx_arrow_chunked_get_uint \
  irx_arrow_internal_chunked_get_uint
#define irx_arrow_chunked_get_double \
  irx_arrow_internal_chunked_get_double
#define irx_arrow_chunked_chunk \
  irx_arrow_internal_chunked_chunk
#define irx_arrow_chunked_combine \
  irx_arrow_internal_chunked_combine
#define irx_arrow_chunked_slice \
  irx_arrow_internal_chunked_slice
#define irx_arrow_chunked_copy \
  irx_arrow_internal_chunked_copy
#define irx_arrow_chunked_concat \
  irx_arrow_internal_chunked_concat
#define irx_arrow_chunked_equal \
  irx_arrow_internal_chunked_equal

uint32_t irx_arrow_abi_version(void);

irx_arrow_status irx_arrow_runtime_has_feature(
    irx_arrow_runtime_feature_id feature_id,
    uint32_t required_contract_version,
    int32_t* out_available,
    uint32_t* out_supported_contract_version);

irx_arrow_status_category irx_arrow_status_get_category(
    irx_arrow_status status);

irx_arrow_status irx_arrow_handle_kind_of(
    const void* handle,
    irx_arrow_handle_kind* out_kind);

irx_arrow_status irx_arrow_handle_ownership_of(
    const void* handle,
    irx_arrow_handle_ownership* out_ownership);

irx_arrow_status irx_arrow_error_snapshot(
    irx_arrow_error_handle** out_error);

irx_arrow_status irx_arrow_error_code(
    const irx_arrow_error_handle* error);

const char* irx_arrow_error_operation(
    const irx_arrow_error_handle* error);

const char* irx_arrow_error_message(
    const irx_arrow_error_handle* error);

const char* irx_arrow_error_upstream_detail(
    const irx_arrow_error_handle* error);

irx_arrow_status irx_arrow_error_retain(
    const irx_arrow_error_handle* error,
    irx_arrow_error_handle** out_error);

irx_arrow_status irx_arrow_error_release(
    irx_arrow_error_handle** error);

irx_arrow_status irx_arrow_schema_import_copy(
    const struct ArrowSchema* schema,
    irx_arrow_schema_handle** out_schema);

irx_arrow_status irx_arrow_schema_export(
    const irx_arrow_schema_handle* schema,
    struct ArrowSchema* out_schema);

int32_t irx_arrow_schema_type_id(
    const irx_arrow_schema_handle* schema);

int32_t irx_arrow_schema_is_nullable(
    const irx_arrow_schema_handle* schema);

irx_arrow_status irx_arrow_schema_retain(
    const irx_arrow_schema_handle* schema,
    irx_arrow_schema_handle** out_schema);

irx_arrow_status irx_arrow_schema_release(
    irx_arrow_schema_handle** schema);

irx_arrow_status irx_arrow_array_builder_new(
    int32_t type_id,
    irx_arrow_array_builder_handle** out_builder);

irx_arrow_status irx_arrow_array_builder_append_null(
    irx_arrow_array_builder_handle* builder,
    int64_t count);

irx_arrow_status irx_arrow_array_builder_append_int(
    irx_arrow_array_builder_handle* builder,
    int64_t value);

irx_arrow_status irx_arrow_array_builder_append_uint(
    irx_arrow_array_builder_handle* builder,
    uint64_t value);

irx_arrow_status irx_arrow_array_builder_append_double(
    irx_arrow_array_builder_handle* builder,
    double value);

irx_arrow_status irx_arrow_array_builder_int32_new(
    irx_arrow_array_builder_handle** out_builder);

irx_arrow_status irx_arrow_array_builder_append_int32(
    irx_arrow_array_builder_handle* builder,
    int32_t value);

irx_arrow_status irx_arrow_array_builder_finish(
    irx_arrow_array_builder_handle** builder,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_builder_release(
    irx_arrow_array_builder_handle** builder);

int64_t irx_arrow_array_length(
    const irx_arrow_array_handle* array);

int64_t irx_arrow_array_offset(
    const irx_arrow_array_handle* array);

int64_t irx_arrow_array_null_count(
    const irx_arrow_array_handle* array);

int32_t irx_arrow_array_type_id(
    const irx_arrow_array_handle* array);

int32_t irx_arrow_array_is_nullable(
    const irx_arrow_array_handle* array);

int32_t irx_arrow_array_has_validity_bitmap(
    const irx_arrow_array_handle* array);

int32_t irx_arrow_array_can_borrow_buffer_view(
    const irx_arrow_array_handle* array);

irx_arrow_status irx_arrow_array_schema_copy(
    const irx_arrow_array_handle* array,
    irx_arrow_schema_handle** out_schema);

irx_arrow_status irx_arrow_array_export(
    const irx_arrow_array_handle* array,
    struct ArrowArray* out_array,
    struct ArrowSchema* out_schema);

irx_arrow_status irx_arrow_array_import(
    const struct ArrowArray* array,
    const struct ArrowSchema* schema,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_import_copy(
    const struct ArrowArray* array,
    const struct ArrowSchema* schema,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_import_move(
    struct ArrowArray* array,
    struct ArrowSchema* schema,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_validity_bitmap(
    const irx_arrow_array_handle* array,
    const void** out_data,
    int64_t* out_offset_bits,
    int64_t* out_length_bits);

irx_arrow_status irx_arrow_array_borrow_buffer_view(
    const irx_arrow_array_handle* array,
    irx_buffer_view* out_view);

irx_arrow_status irx_arrow_array_retain(
    const irx_arrow_array_handle* array,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_release(
    irx_arrow_array_handle** array);

irx_arrow_status irx_arrow_record_batch_import_move(
    struct ArrowArray* array,
    struct ArrowSchema* schema,
    irx_arrow_record_batch_handle** out_batch);

irx_arrow_status irx_arrow_record_batch_export(
    const irx_arrow_record_batch_handle* batch,
    struct ArrowArray* out_array,
    struct ArrowSchema* out_schema);

int64_t irx_arrow_record_batch_num_rows(
    const irx_arrow_record_batch_handle* batch);

int64_t irx_arrow_record_batch_num_columns(
    const irx_arrow_record_batch_handle* batch);

irx_arrow_status irx_arrow_record_batch_retain(
    const irx_arrow_record_batch_handle* batch,
    irx_arrow_record_batch_handle** out_batch);

irx_arrow_status irx_arrow_record_batch_release(
    irx_arrow_record_batch_handle** batch);

irx_arrow_status irx_arrow_tensor_builder_new(
    int32_t type_id,
    int32_t ndim,
    const int64_t* shape,
    const int64_t* strides,
    irx_arrow_tensor_builder_handle** out_builder);

irx_arrow_status irx_arrow_tensor_builder_append_int(
    irx_arrow_tensor_builder_handle* builder,
    int64_t value);

irx_arrow_status irx_arrow_tensor_builder_append_uint(
    irx_arrow_tensor_builder_handle* builder,
    uint64_t value);

irx_arrow_status irx_arrow_tensor_builder_append_double(
    irx_arrow_tensor_builder_handle* builder,
    double value);

irx_arrow_status irx_arrow_tensor_builder_finish(
    irx_arrow_tensor_builder_handle** builder,
    irx_arrow_tensor_handle** out_tensor);

irx_arrow_status irx_arrow_tensor_builder_release(
    irx_arrow_tensor_builder_handle** builder);

int32_t irx_arrow_tensor_type_id(
    const irx_arrow_tensor_handle* tensor);

int32_t irx_arrow_tensor_ndim(
    const irx_arrow_tensor_handle* tensor);

int64_t irx_arrow_tensor_size(
    const irx_arrow_tensor_handle* tensor);

const int64_t* irx_arrow_tensor_shape(
    const irx_arrow_tensor_handle* tensor);

const int64_t* irx_arrow_tensor_strides(
    const irx_arrow_tensor_handle* tensor);

irx_arrow_status irx_arrow_tensor_borrow_buffer_view(
    const irx_arrow_tensor_handle* tensor,
    irx_buffer_view* out_view);

irx_arrow_status irx_arrow_tensor_retain(
    const irx_arrow_tensor_handle* tensor,
    irx_arrow_tensor_handle** out_tensor);

irx_arrow_status irx_arrow_tensor_release(
    irx_arrow_tensor_handle** tensor);

irx_arrow_status irx_arrow_table_new_from_arrays(
    int64_t column_count,
    const char** names,
    irx_arrow_array_handle** arrays,
    irx_arrow_table_handle** out_table);

int64_t irx_arrow_table_num_rows(
    const irx_arrow_table_handle* table);

int64_t irx_arrow_table_num_columns(
    const irx_arrow_table_handle* table);

irx_arrow_status irx_arrow_table_column_by_name(
    const irx_arrow_table_handle* table,
    const char* name,
    irx_arrow_chunked_array_handle** out_column);

irx_arrow_status irx_arrow_table_column_by_index(
    const irx_arrow_table_handle* table,
    int32_t index,
    irx_arrow_chunked_array_handle** out_column);

irx_arrow_status irx_arrow_table_retain(
    const irx_arrow_table_handle* table,
    irx_arrow_table_handle** out_table);

irx_arrow_status irx_arrow_table_release(
    irx_arrow_table_handle** table);

irx_arrow_status irx_arrow_chunked_array_retain(
    const irx_arrow_chunked_array_handle* column,
    irx_arrow_chunked_array_handle** out_column);

irx_arrow_status irx_arrow_chunked_array_release(
    irx_arrow_chunked_array_handle** column);

void irx_arrow_tensor_release_callback(
    void* tensor);

const char* irx_arrow_last_error(void);

irx_arrow_status irx_arrow_type_import_copy(
    const struct ArrowSchema* schema,
    irx_arrow_type_handle** out_value);

irx_arrow_status irx_arrow_type_export(
    const irx_arrow_type_handle* value,
    struct ArrowSchema* out_schema);

irx_arrow_status irx_arrow_type_retain(
    const irx_arrow_type_handle* value,
    irx_arrow_type_handle** out_value);

irx_arrow_status irx_arrow_type_release(
    irx_arrow_type_handle** value);

irx_arrow_status irx_arrow_field_import_copy(
    const struct ArrowSchema* schema,
    irx_arrow_field_handle** out_value);

irx_arrow_status irx_arrow_field_export(
    const irx_arrow_field_handle* value,
    struct ArrowSchema* out_schema);

irx_arrow_status irx_arrow_field_retain(
    const irx_arrow_field_handle* value,
    irx_arrow_field_handle** out_value);

irx_arrow_status irx_arrow_field_release(
    irx_arrow_field_handle** value);

irx_arrow_status irx_arrow_type_equals(
    const irx_arrow_type_handle* left,
    const irx_arrow_type_handle* right,
    int32_t* out_equal);

irx_arrow_status irx_arrow_field_equals(
    const irx_arrow_field_handle* left,
    const irx_arrow_field_handle* right,
    int32_t* out_equal);

irx_arrow_status irx_arrow_schema_equals(
    const irx_arrow_schema_handle* left,
    const irx_arrow_schema_handle* right,
    int32_t* out_equal);

irx_arrow_status irx_arrow_type_num_fields(
    const irx_arrow_type_handle* value,
    int64_t* out_count);

irx_arrow_status irx_arrow_type_field(
    const irx_arrow_type_handle* value,
    int64_t index,
    irx_arrow_field_handle** out_field);

irx_arrow_status irx_arrow_schema_num_fields(
    const irx_arrow_schema_handle* value,
    int64_t* out_count);

irx_arrow_status irx_arrow_schema_field(
    const irx_arrow_schema_handle* value,
    int64_t index,
    irx_arrow_field_handle** out_field);

irx_arrow_status irx_arrow_field_type(
    const irx_arrow_field_handle* value,
    irx_arrow_type_handle** out_type);

irx_arrow_status irx_arrow_field_nullable(
    const irx_arrow_field_handle* value,
    int32_t* out_nullable);

irx_arrow_status irx_arrow_type_bit_width(
    const irx_arrow_type_handle* value,
    int64_t* out_width);

irx_arrow_status irx_arrow_field_name_copy(
    const irx_arrow_field_handle* value,
    const char** out_name);

irx_arrow_status irx_arrow_array_get_int(
    const irx_arrow_array_handle* array,
    int64_t index,
    int32_t* out_valid,
    int64_t* out_value);

irx_arrow_status irx_arrow_array_get_uint(
    const irx_arrow_array_handle* array,
    int64_t index,
    int32_t* out_valid,
    uint64_t* out_value);

irx_arrow_status irx_arrow_array_get_double(
    const irx_arrow_array_handle* array,
    int64_t index,
    int32_t* out_valid,
    double* out_value);

irx_arrow_status irx_arrow_array_slice(
    const irx_arrow_array_handle* array,
    int64_t offset,
    int64_t length,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_concat(
    const irx_arrow_array_handle* lhs,
    const irx_arrow_array_handle* rhs,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_copy(
    const irx_arrow_array_handle* array,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_equal(
    const irx_arrow_array_handle* lhs,
    const irx_arrow_array_handle* rhs,
    int32_t* out_equal);

irx_arrow_status irx_arrow_array_builder_finish_typed(
    irx_arrow_array_builder_handle** builder,
    int32_t nullable,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_array_builder_reserve(
    irx_arrow_array_builder_handle* builder,
    int64_t additional);

irx_arrow_status irx_arrow_array_builder_length(
    const irx_arrow_array_builder_handle* builder,
    int64_t* out_length);

irx_arrow_status irx_arrow_array_builder_build(
    irx_arrow_array_builder_handle* builder,
    int32_t nullable,
    irx_arrow_array_handle** out_array);

irx_arrow_status irx_arrow_chunked_new(
    int32_t type_id,
    int32_t nullable,
    const void** chunks,
    int64_t count,
    irx_arrow_chunked_array_handle** out_value);

irx_arrow_status irx_arrow_chunked_length(
    const irx_arrow_chunked_array_handle* value,
    int64_t* output);

irx_arrow_status irx_arrow_chunked_null_count(
    const irx_arrow_chunked_array_handle* value,
    int64_t* output);

irx_arrow_status irx_arrow_chunked_num_chunks(
    const irx_arrow_chunked_array_handle* value,
    int64_t* output);

irx_arrow_status irx_arrow_chunked_get_int(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    int32_t* valid,
    int64_t* output);

irx_arrow_status irx_arrow_chunked_get_uint(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    int32_t* valid,
    uint64_t* output);

irx_arrow_status irx_arrow_chunked_get_double(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    int32_t* valid,
    double* output);

irx_arrow_status irx_arrow_chunked_chunk(
    const irx_arrow_chunked_array_handle* value,
    int64_t index,
    irx_arrow_array_handle** output);

irx_arrow_status irx_arrow_chunked_combine(
    const irx_arrow_chunked_array_handle* value,
    irx_arrow_array_handle** output);

irx_arrow_status irx_arrow_chunked_slice(
    const irx_arrow_chunked_array_handle* value,
    int64_t offset,
    int64_t length,
    irx_arrow_chunked_array_handle** output);

irx_arrow_status irx_arrow_chunked_copy(
    const irx_arrow_chunked_array_handle* value,
    irx_arrow_chunked_array_handle** output);

irx_arrow_status irx_arrow_chunked_concat(
    const irx_arrow_chunked_array_handle* lhs,
    const irx_arrow_chunked_array_handle* rhs,
    irx_arrow_chunked_array_handle** output);

irx_arrow_status irx_arrow_chunked_equal(
    const irx_arrow_chunked_array_handle* lhs,
    const irx_arrow_chunked_array_handle* rhs,
    int32_t* output);


#endif
